### ISSUE TITLE
Ansible modules

### ISSUE THREAD

**Issue by AnBuKu** [debops/docs#206]
Add Ansible modules, respective its name with hyperlink - All and/or simply the relevant ones per DebOps role - at appropriate places in DebOps documentation in oder to increase benefit of DebOps for its Users.

**Comment by drybjed** [comment]
I think this could be automated via the API, since list of modules used in a role is known and should be relatively easy to parse. Maybe each DebOps role could get its own augenerated page on https://debops.org/status/? Actually, the status page and related ones could be moved to a separate git repository and published at htps://qa.debops.org/ to make management easier.

**Comment by ypid** [comment]
I don’t see the big benefit this would give users to add a list of all used Ansible modules. If users want to know that, they can just grep for it or run the role in check mode.

Something which is related to this is that we already have a URL list of all official Ansible modules to use in role documentation. https://github.com/debops/docs/blob/master/docs/includes/30gen_ansible_modules.rst

**Comment by AnBuKu** [comment]
The opening of this issue was based onto notices of IRC talks/questions and the assumption, that anybody likes ease of use:
- SysAdmins new to DebOps  or/and in a hurry, do not know about Ansible modules or how they relate to DebOps roles, thus ask (unnecessary?) questions in IRC.
- No overview of complete DebOps/Ansible tool-chain, but  [DebOps Status](https://debops.org/status) as a good starter.
- No fast food, but easy to follow, complete from A-Z and intuitive cooking recipes, might help to enjoy a recurrent and reproducible sense of achievement.
- Interpretation of github.com/debops as a workbench and source for **DebOps** documentation, the nicely dressed and easy to use display window.
- Automated implementation and maintenance of Ansible Modules entry or entries in docs.debops.org is must; preferably by one feed out of github, e.g 30gen_ansible_modules.rst (?)

When ypid writes "If users want to know that, they can just grep for it or run the role in check mode." he certainly means quite experienced SysAdmins. Newbies, in any term, might unnecessarily struggle, as they have to do an additional search/task in oder to find 30gen_ansible_modules.rst what is in github only, but not in debops.org; at least I got no result, when searching _Ansible Module_ or _Module_ or _Modules_ in docs.debops.org 

My suggestion is, to have three places to mention Ansible Modules on [DebOps](https://www.debops.org):
1.  Add sub-section _Ansible Modules_ or _Modules_ to Template _Ansible role: debops.you-name-it_ 
2.  Expand  [DebOps Status](https://debops.org/status) by Ansible Modules. Means links to sub-section on _Ansible role: debops.you-name-it_ 
3. Add page _Ansible modules and DebOps_ (or whatever you think fits best) to [DebOps documentation](https://docs.debops.org)

**Comment by drybjed** [comment]
I don't really understand that concern about "Ansible Modules" in relation to DebOps...

Ansible modules are what DebOps uses to perform its tasks, no more and no less. If you want to know what Ansible modules you can use with DebOps, my answer is - all of them. The modules are bundled with Ansible installation, you can find their documentation in [official Ansible documentation](https://docs.ansible.com/ansible/modules_by_category.html). I'm not really sure that DebOps documentation should concern itself with the specific modules that are used - modules get replaced, tasks that are done by a role change, but from the "higher level" of the playbooks, it doesn't really matter what modules a particular role uses to do its job.

Sure, I imagine that if you want to change some roles, or write new ones, you will want to learn about modules. But at this point you need to learn about Ansible itself as well. Does that mean that DebOps needs to include whole Ansible documentation in its own documentation? I don't believe so.

**Comment by AnBuKu** [comment]
It's not a concern about Ansible Modules, _but only_ about DebOps newbies or lazy DebOps users and nothing more. :-)

And no, I have no intention at all to replace Ansible documentation. - E.g. place three in DebOps mentioned above might only have a link to Ansible documentation.

**Comment by ypid** [comment]
There are two things which I think are beneficial to users of DebOps and we doing that to do that (or at least started):

1. When an inventory variable allows nearly direct usage of an underlying Ansible module, it should be referred to in the documentation. Example [Default variables of debops.resources](https://docs.debops.org/en/latest/ansible/roles/ansible-resources/docs/defaults.html). This is where the `30gen_ansible_modules.rst` comes into play because you can just write:

  ```rst
  `Ansible file module`_
  ```

  and the DebOps documentation makes it a hyperlink and allows to easily maintain the targets of those hyperlinks.

2. When custom Ansible modules are used which are not included in Ansible (yet), the docs should note that. This should also be known practice. Or at least a quick internet search should be able to answer that by now because it has been answered a number of times.

**Comment by AnBuKu** [comment]
So, conclusion: No need to change something or to add something. Thus, I close the issue

Sorry for rising up the issue.
